name: Build Windows

on:
  push:
    branches: [main, master]
  pull_request:

jobs:

  build-windows:

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          make

    - name: Git Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: |
        ABC_USE_STDINT_H=1 cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-DWIN32 -DWIN32_NO_DLL" -DCMAKE_CXX_FLAGS="-DWIN32 -DWIN32_NO_DLL" -DREADLINE_FOUND=FALSE -DABC_SKIP_TESTS=1 -B build

    - name: Build
      run: |
        cmake --build build

    - name: Test Executable
      run: |
        ./build/abc.exe -c "r i10.aig; b; ps; b; rw -l; rw -lz; b; rw -lz; b; ps; cec"

    - name: Stage Executable
      run: |
        mkdir -p staging
        cp build/abc.exe staging/

    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: package-windows
        path: staging/
